/*
 * Radix job scheduler server.
 *
 * This is the API Server for the Radix job scheduler server.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = RadixJobClient.Client.OpenAPIDateConverter;

namespace RadixJobClient.Model
{
    /// <summary>
    /// ReplicaStatus describes the status of a component container inside a pod
    /// </summary>
    [DataContract(Name = "ReplicaStatus")]
    public partial class ReplicaStatus : IEquatable<ReplicaStatus>, IValidatableObject
    {
        /// <summary>
        /// Status of the container Pending &#x3D; Container in Waiting state and the reason is ContainerCreating Failed &#x3D; Container is failed Failing &#x3D; Container is failed Running &#x3D; Container in Running state Succeeded &#x3D; Container in Succeeded state Terminated &#x3D; Container in Terminated state
        /// </summary>
        /// <value>Status of the container Pending &#x3D; Container in Waiting state and the reason is ContainerCreating Failed &#x3D; Container is failed Failing &#x3D; Container is failed Running &#x3D; Container in Running state Succeeded &#x3D; Container in Succeeded state Terminated &#x3D; Container in Terminated state</value>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum StatusEnum
        {
            /// <summary>
            /// Enum Pending for value: Pending
            /// </summary>
            [EnumMember(Value = "Pending")]
            Pending = 1,

            /// <summary>
            /// Enum Succeeded for value: Succeeded
            /// </summary>
            [EnumMember(Value = "Succeeded")]
            Succeeded = 2,

            /// <summary>
            /// Enum Failing for value: Failing
            /// </summary>
            [EnumMember(Value = "Failing")]
            Failing = 3,

            /// <summary>
            /// Enum Failed for value: Failed
            /// </summary>
            [EnumMember(Value = "Failed")]
            Failed = 4,

            /// <summary>
            /// Enum Running for value: Running
            /// </summary>
            [EnumMember(Value = "Running")]
            Running = 5,

            /// <summary>
            /// Enum Terminated for value: Terminated
            /// </summary>
            [EnumMember(Value = "Terminated")]
            Terminated = 6,

            /// <summary>
            /// Enum Starting for value: Starting
            /// </summary>
            [EnumMember(Value = "Starting")]
            Starting = 7

        }


        /// <summary>
        /// Status of the container Pending &#x3D; Container in Waiting state and the reason is ContainerCreating Failed &#x3D; Container is failed Failing &#x3D; Container is failed Running &#x3D; Container in Running state Succeeded &#x3D; Container in Succeeded state Terminated &#x3D; Container in Terminated state
        /// </summary>
        /// <value>Status of the container Pending &#x3D; Container in Waiting state and the reason is ContainerCreating Failed &#x3D; Container is failed Failing &#x3D; Container is failed Running &#x3D; Container in Running state Succeeded &#x3D; Container in Succeeded state Terminated &#x3D; Container in Terminated state</value>
        [DataMember(Name = "status", IsRequired = true, EmitDefaultValue = false)]
        public StatusEnum Status { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="ReplicaStatus" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected ReplicaStatus() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="ReplicaStatus" /> class.
        /// </summary>
        /// <param name="status">Status of the container Pending &#x3D; Container in Waiting state and the reason is ContainerCreating Failed &#x3D; Container is failed Failing &#x3D; Container is failed Running &#x3D; Container in Running state Succeeded &#x3D; Container in Succeeded state Terminated &#x3D; Container in Terminated state (required).</param>
        public ReplicaStatus(StatusEnum status = default(StatusEnum))
        {
            this.Status = status;
        }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class ReplicaStatus {\n");
            sb.Append("  Status: ").Append(Status).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as ReplicaStatus);
        }

        /// <summary>
        /// Returns true if ReplicaStatus instances are equal
        /// </summary>
        /// <param name="input">Instance of ReplicaStatus to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(ReplicaStatus input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Status == input.Status ||
                    this.Status.Equals(input.Status)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                hashCode = hashCode * 59 + this.Status.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        public IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
