apiVersion: radix.equinor.com/v1
kind: RadixApplication
metadata:
  name: radix-job-demo
spec:
  privateImageHubs:
    radixcanary.azurecr.io:
      username: 814607e6-3d71-44a7-8476-50e8b281abbc
  dnsExternalAlias:
    - alias: myapp2.dev.radix.equinor.com
      component: server
      environment: qa
  build:
    useBuildKit: true
    secrets:
      - SECRET1
  dnsAppAlias:
    environment: qa
    component: server
  environments:
    - name: dev
      build:
        from: main
    - name: qa
      build:
        from: main
    - name: prod
      build:
        from: release
  jobs:
    - name: "compute"
      src: "compute"
      schedulerPort: 8080
      timeLimitSeconds: 300
      backoffLimit: 0
      notifications:
        webhook: http://server:6000/api/notification/job
      ports:
        - name: http
          port: 9999
        - name: metrics2
          port: 9090
      monitoringConfig:
        portName: metrics2
      payload:
        path: "/compute/args"
      identity:
        azure:
          clientId: 5e48ca1f-a2bf-4dec-b96d-bbf8ce69f9f6
      variables:
        COMPUTE_CONFIG: "/compute/args/payload"
        CALLBACK_ON_COMPLETE_URL: "http://server:5000"
        SQL_SERVER_NAME: "fed-test.database.windows.net"
        SQL_DATABASE_NAME: "fed-test"
      environmentConfig:
        - environment: prod
          identity:
            azure:
              clientId: b96d264b-7053-4465-a4a7-32be5b0fec49
        - environment: qa
          monitoring: true
          backoffLimit: 0
  components:
    - name: "server"
      src: src
      dockerfileName: Dockerfile.frontend
      ports:
        - name: http
          port: 5000
        - name: notification
          port: 6000
      publicPort: http
      variables:
        ASPNETCORE_URLS: "http://*:5000;http://*:6000"
        JOB_SCHEDULER: "http://compute:8080"
        COMPUTE_IMAGE_PATH: "/app/computeimages"
      identity:
        azure:
          clientId: 5e48ca1f-a2bf-4dec-b96d-bbf8ce69f9f6
      authentication:
        oauth2:
          clientId: 5e48ca1f-a2bf-4dec-b96d-bbf8ce69f9f6
          scope: openid email profile offline_access
          sessionStoreType: redis
          redisStore:
            connectionUrl: redis://redis:6379
      ingressConfiguration:
        - stickysessions
      resources:
        requests:
          memory: "201M"
          cpu: "50m"
        limits:
          memory: "500M"
    - name: redis
      image: bitnami/redis:{imageTagName}
      environmentConfig:
        - environment: dev
          imageTagName: "7.2"
        - environment: qa
          imageTagName: "7.2"          
        - environment: prod
          imageTagName: "7.0"
      alwaysPullImageOnDeploy: true
      ports:
        - name: redis
          port: 6379
      secrets:
        - REDIS_PASSWORD
      resources:
        requests:
          memory: "100M"
          cpu: "50m"
        limits:
          memory: "200M"

