apiVersion: radix.equinor.com/v1
kind: RadixApplication
metadata:
  name: radix-job-demo
spec:
  environments:
    - name: qa
      build:
        from: main
  jobs:
    - name: "compute"
      src: "./compute"
      schedulerPort: 8080
      payload:
        path: "/compute/payload"
      variables:
        COMPUTE_CONFIG: "/compute/payload/payload"
        COMPUTE_OUT_PATH: "/dist/computeimages"
      environmentConfig:
        - environment: qa
          volumeMounts:
            - type: blob
              name: storage
              container: blobfusevolumetestdata3
              path: /dist/computeimages
  components:
    - name: "server"
      src: "./frontend"
      variables:
        ASPNETCORE_URLS: "http://*:5005"
        JOB_SCHEDULER: "http://compute:8080"
        COMPUTE_IMAGE_PATH: "/computeimages"
      ports:
        - name: http
          port: 5005
      public: false
      environmentConfig:
        - environment: qa
          volumeMounts:
            - type: blob
              name: storage
              container: blobfusevolumetestdata3
              path: /computeimages
