apiVersion: radix.equinor.com/v1
kind: RadixScheduledJob
metadata:
  name: compute-20221212143712-abcdefgh
  namespace:
spec:
  jobId: some-custom-id
  radixDeploymentJobRef:
    name: qa-nhqkk-qd75t1df
    job: compute
  payloadSecretRef:
    name: compute-20221212143712-abcdefgh-secret
    key: payload
  # job config (inline)
  timeLimitSeconds: 300
  resources:
    requests:
    limits:
  node:
    gpu:
    gpuCount:
---
apiVersion: radix.equinor.com/v1
kind: RadixBatchJob
metadata:
  name: batch-compute-20221212143712-abcdefgh
  namespace:
spec:
  # job default config (inline)
  timeLimitSeconds: 300
  resources:
    requests:
    limits:
  node:
    gpu:
    gpuCount:
  jobs:
    - jobId: some-custom-id1
      radixDeploymentJobRef:
        name: qa-nhqkk-qd75t1df
        job: compute
      payloadSecretRef:
        name: compute-batch-20221212143712-abcdefgh-secret1
        key: payload
    - jobId: some-custom-id2
      radixDeploymentJobRef:
        name: qa-nhqkk-qd75t1df
        job: compute
      payloadSecretRef:
        name: compute-batch-20221212143712-abcdefgh-secret2
        key: payload
    - radixDeploymentJobRef:
        name: qa-nhqkk-qd75t1df
        job: compute
      payloadSecretRef:
        name: compute-batch-20221212143712-abcdefgh-secret2
        key: payload        