/*
 * classification Radix API.
 *
 * This is the API Server for the Radix job scheduler.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using RadixJobClient.Api;
using RadixJobClient.Model;
using RadixJobClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace RadixJobClient.Test.Model
{
    /// <summary>
    ///  Class for testing RadixJobComponentConfig
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class RadixJobComponentConfigTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for RadixJobComponentConfig
        //private RadixJobComponentConfig instance;

        public RadixJobComponentConfigTests()
        {
            // TODO uncomment below to create an instance of RadixJobComponentConfig
            //instance = new RadixJobComponentConfig();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of RadixJobComponentConfig
        /// </summary>
        [Fact]
        public void RadixJobComponentConfigInstanceTest()
        {
            // TODO uncomment below to test "IsType" RadixJobComponentConfig
            //Assert.IsType<RadixJobComponentConfig>(instance);
        }


        /// <summary>
        /// Test the property 'Node'
        /// </summary>
        [Fact]
        public void NodeTest()
        {
            // TODO unit test for the property 'Node'
        }
        /// <summary>
        /// Test the property 'Resources'
        /// </summary>
        [Fact]
        public void ResourcesTest()
        {
            // TODO unit test for the property 'Resources'
        }

    }

}
