/*
 * classification Radix API.
 *
 * This is the API Server for the Radix job scheduler.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using RadixJobClient.Api;
using RadixJobClient.Model;
using RadixJobClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace RadixJobClient.Test.Model
{
    /// <summary>
    ///  Class for testing RadixNode
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class RadixNodeTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for RadixNode
        //private RadixNode instance;

        public RadixNodeTests()
        {
            // TODO uncomment below to create an instance of RadixNode
            //instance = new RadixNode();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of RadixNode
        /// </summary>
        [Fact]
        public void RadixNodeInstanceTest()
        {
            // TODO uncomment below to test "IsType" RadixNode
            //Assert.IsType<RadixNode>(instance);
        }


        /// <summary>
        /// Test the property 'Gpu'
        /// </summary>
        [Fact]
        public void GpuTest()
        {
            // TODO unit test for the property 'Gpu'
        }
        /// <summary>
        /// Test the property 'GpuCount'
        /// </summary>
        [Fact]
        public void GpuCountTest()
        {
            // TODO unit test for the property 'GpuCount'
        }

    }

}
