:: Generated by: https://openapi-generator.tech
::

@echo off

dotnet restore src\RadixJobServer
dotnet build src\RadixJobServer
echo Now, run the following to start the project: dotnet run -p src\RadixJobServer\RadixJobServer.csproj --launch-profile web.
echo.
