/*
 * Radix job scheduler server.
 *
 * This is the API Server for the Radix job scheduler server.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using RadixJobClient.Api;
using RadixJobClient.Model;
using RadixJobClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace RadixJobClient.Test.Model
{
    /// <summary>
    ///  Class for testing BatchScheduleDescription
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class BatchScheduleDescriptionTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for BatchScheduleDescription
        //private BatchScheduleDescription instance;

        public BatchScheduleDescriptionTests()
        {
            // TODO uncomment below to create an instance of BatchScheduleDescription
            //instance = new BatchScheduleDescription();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of BatchScheduleDescription
        /// </summary>
        [Fact]
        public void BatchScheduleDescriptionInstanceTest()
        {
            // TODO uncomment below to test "IsType" BatchScheduleDescription
            //Assert.IsType<BatchScheduleDescription>(instance);
        }


        /// <summary>
        /// Test the property 'DefaultRadixJobComponentConfig'
        /// </summary>
        [Fact]
        public void DefaultRadixJobComponentConfigTest()
        {
            // TODO unit test for the property 'DefaultRadixJobComponentConfig'
        }
        /// <summary>
        /// Test the property 'JobScheduleDescriptions'
        /// </summary>
        [Fact]
        public void JobScheduleDescriptionsTest()
        {
            // TODO unit test for the property 'JobScheduleDescriptions'
        }

    }

}
