/*
 * Radix job scheduler server.
 *
 * This is the API Server for the Radix job scheduler server.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using RadixJobClient.Model;
using RadixJobClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace RadixJobClient.Test.Model
{
    /// <summary>
    ///  Class for testing FailurePolicyRule
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class FailurePolicyRuleTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for FailurePolicyRule
        //private FailurePolicyRule instance;

        public FailurePolicyRuleTests()
        {
            // TODO uncomment below to create an instance of FailurePolicyRule
            //instance = new FailurePolicyRule();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of FailurePolicyRule
        /// </summary>
        [Fact]
        public void FailurePolicyRuleInstanceTest()
        {
            // TODO uncomment below to test "IsType" FailurePolicyRule
            //Assert.IsType<FailurePolicyRule>(instance);
        }

        /// <summary>
        /// Test the property 'Action'
        /// </summary>
        [Fact]
        public void ActionTest()
        {
            // TODO unit test for the property 'Action'
        }

        /// <summary>
        /// Test the property 'OnExitCodes'
        /// </summary>
        [Fact]
        public void OnExitCodesTest()
        {
            // TODO unit test for the property 'OnExitCodes'
        }
    }
}
