/*
 * Radix job scheduler server.
 *
 * This is the API Server for the Radix job scheduler server.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using RadixJobClient.Model;
using RadixJobClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace RadixJobClient.Test.Model
{
    /// <summary>
    ///  Class for testing FailurePolicy
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class FailurePolicyTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for FailurePolicy
        //private FailurePolicy instance;

        public FailurePolicyTests()
        {
            // TODO uncomment below to create an instance of FailurePolicy
            //instance = new FailurePolicy();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of FailurePolicy
        /// </summary>
        [Fact]
        public void FailurePolicyInstanceTest()
        {
            // TODO uncomment below to test "IsType" FailurePolicy
            //Assert.IsType<FailurePolicy>(instance);
        }

        /// <summary>
        /// Test the property 'Rules'
        /// </summary>
        [Fact]
        public void RulesTest()
        {
            // TODO unit test for the property 'Rules'
        }
    }
}
