/*
 * Radix job scheduler server.
 *
 * This is the API Server for the Radix job scheduler server.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using RadixJobClient.Model;
using RadixJobClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace RadixJobClient.Test.Model
{
    /// <summary>
    ///  Class for testing FailurePolicyRuleOnExitCodes
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class FailurePolicyRuleOnExitCodesTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for FailurePolicyRuleOnExitCodes
        //private FailurePolicyRuleOnExitCodes instance;

        public FailurePolicyRuleOnExitCodesTests()
        {
            // TODO uncomment below to create an instance of FailurePolicyRuleOnExitCodes
            //instance = new FailurePolicyRuleOnExitCodes();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of FailurePolicyRuleOnExitCodes
        /// </summary>
        [Fact]
        public void FailurePolicyRuleOnExitCodesInstanceTest()
        {
            // TODO uncomment below to test "IsType" FailurePolicyRuleOnExitCodes
            //Assert.IsType<FailurePolicyRuleOnExitCodes>(instance);
        }

        /// <summary>
        /// Test the property 'Operator'
        /// </summary>
        [Fact]
        public void OperatorTest()
        {
            // TODO unit test for the property 'Operator'
        }

        /// <summary>
        /// Test the property 'Values'
        /// </summary>
        [Fact]
        public void ValuesTest()
        {
            // TODO unit test for the property 'Values'
        }
    }
}
