/*
 * Radix job scheduler server.
 *
 * This is the API Server for the Radix job scheduler server.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using RadixJobClient.Model;
using RadixJobClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace RadixJobClient.Test.Model
{
    /// <summary>
    ///  Class for testing JobStatus
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class JobStatusTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for JobStatus
        //private JobStatus instance;

        public JobStatusTests()
        {
            // TODO uncomment below to create an instance of JobStatus
            //instance = new JobStatus();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of JobStatus
        /// </summary>
        [Fact]
        public void JobStatusInstanceTest()
        {
            // TODO uncomment below to test "IsType" JobStatus
            //Assert.IsType<JobStatus>(instance);
        }

        /// <summary>
        /// Test the property 'DeploymentName'
        /// </summary>
        [Fact]
        public void DeploymentNameTest()
        {
            // TODO unit test for the property 'DeploymentName'
        }

        /// <summary>
        /// Test the property 'BatchId'
        /// </summary>
        [Fact]
        public void BatchIdTest()
        {
            // TODO unit test for the property 'BatchId'
        }

        /// <summary>
        /// Test the property 'BatchName'
        /// </summary>
        [Fact]
        public void BatchNameTest()
        {
            // TODO unit test for the property 'BatchName'
        }

        /// <summary>
        /// Test the property 'Created'
        /// </summary>
        [Fact]
        public void CreatedTest()
        {
            // TODO unit test for the property 'Created'
        }

        /// <summary>
        /// Test the property 'Ended'
        /// </summary>
        [Fact]
        public void EndedTest()
        {
            // TODO unit test for the property 'Ended'
        }

        /// <summary>
        /// Test the property 'Failed'
        /// </summary>
        [Fact]
        public void FailedTest()
        {
            // TODO unit test for the property 'Failed'
        }

        /// <summary>
        /// Test the property 'JobId'
        /// </summary>
        [Fact]
        public void JobIdTest()
        {
            // TODO unit test for the property 'JobId'
        }

        /// <summary>
        /// Test the property 'Message'
        /// </summary>
        [Fact]
        public void MessageTest()
        {
            // TODO unit test for the property 'Message'
        }

        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }

        /// <summary>
        /// Test the property 'PodStatuses'
        /// </summary>
        [Fact]
        public void PodStatusesTest()
        {
            // TODO unit test for the property 'PodStatuses'
        }

        /// <summary>
        /// Test the property 'Restart'
        /// </summary>
        [Fact]
        public void RestartTest()
        {
            // TODO unit test for the property 'Restart'
        }

        /// <summary>
        /// Test the property 'Started'
        /// </summary>
        [Fact]
        public void StartedTest()
        {
            // TODO unit test for the property 'Started'
        }

        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Fact]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }

        /// <summary>
        /// Test the property 'Updated'
        /// </summary>
        [Fact]
        public void UpdatedTest()
        {
            // TODO unit test for the property 'Updated'
        }
    }
}
