/*
 * Radix job scheduler server.
 *
 * This is the API Server for the Radix job scheduler server.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using RadixJobClient.Model;
using RadixJobClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace RadixJobClient.Test.Model
{
    /// <summary>
    ///  Class for testing JobScheduleDescription
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class JobScheduleDescriptionTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for JobScheduleDescription
        //private JobScheduleDescription instance;

        public JobScheduleDescriptionTests()
        {
            // TODO uncomment below to create an instance of JobScheduleDescription
            //instance = new JobScheduleDescription();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of JobScheduleDescription
        /// </summary>
        [Fact]
        public void JobScheduleDescriptionInstanceTest()
        {
            // TODO uncomment below to test "IsType" JobScheduleDescription
            //Assert.IsType<JobScheduleDescription>(instance);
        }

        /// <summary>
        /// Test the property 'BackoffLimit'
        /// </summary>
        [Fact]
        public void BackoffLimitTest()
        {
            // TODO unit test for the property 'BackoffLimit'
        }

        /// <summary>
        /// Test the property 'FailurePolicy'
        /// </summary>
        [Fact]
        public void FailurePolicyTest()
        {
            // TODO unit test for the property 'FailurePolicy'
        }

        /// <summary>
        /// Test the property 'ImageTagName'
        /// </summary>
        [Fact]
        public void ImageTagNameTest()
        {
            // TODO unit test for the property 'ImageTagName'
        }

        /// <summary>
        /// Test the property 'JobId'
        /// </summary>
        [Fact]
        public void JobIdTest()
        {
            // TODO unit test for the property 'JobId'
        }

        /// <summary>
        /// Test the property 'Node'
        /// </summary>
        [Fact]
        public void NodeTest()
        {
            // TODO unit test for the property 'Node'
        }

        /// <summary>
        /// Test the property 'Payload'
        /// </summary>
        [Fact]
        public void PayloadTest()
        {
            // TODO unit test for the property 'Payload'
        }

        /// <summary>
        /// Test the property 'Resources'
        /// </summary>
        [Fact]
        public void ResourcesTest()
        {
            // TODO unit test for the property 'Resources'
        }

        /// <summary>
        /// Test the property 'TimeLimitSeconds'
        /// </summary>
        [Fact]
        public void TimeLimitSecondsTest()
        {
            // TODO unit test for the property 'TimeLimitSeconds'
        }
    }
}
