/*
 * Radix job scheduler server.
 *
 * This is the API Server for the Radix job scheduler server.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using RadixJobClient.Model;
using RadixJobClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace RadixJobClient.Test.Model
{
    /// <summary>
    ///  Class for testing PodStatus
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PodStatusTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for PodStatus
        //private PodStatus instance;

        public PodStatusTests()
        {
            // TODO uncomment below to create an instance of PodStatus
            //instance = new PodStatus();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of PodStatus
        /// </summary>
        [Fact]
        public void PodStatusInstanceTest()
        {
            // TODO uncomment below to test "IsType" PodStatus
            //Assert.IsType<PodStatus>(instance);
        }

        /// <summary>
        /// Test the property 'ContainerStarted'
        /// </summary>
        [Fact]
        public void ContainerStartedTest()
        {
            // TODO unit test for the property 'ContainerStarted'
        }

        /// <summary>
        /// Test the property 'Created'
        /// </summary>
        [Fact]
        public void CreatedTest()
        {
            // TODO unit test for the property 'Created'
        }

        /// <summary>
        /// Test the property 'EndTime'
        /// </summary>
        [Fact]
        public void EndTimeTest()
        {
            // TODO unit test for the property 'EndTime'
        }

        /// <summary>
        /// Test the property 'ExitCode'
        /// </summary>
        [Fact]
        public void ExitCodeTest()
        {
            // TODO unit test for the property 'ExitCode'
        }

        /// <summary>
        /// Test the property 'Image'
        /// </summary>
        [Fact]
        public void ImageTest()
        {
            // TODO unit test for the property 'Image'
        }

        /// <summary>
        /// Test the property 'ImageId'
        /// </summary>
        [Fact]
        public void ImageIdTest()
        {
            // TODO unit test for the property 'ImageId'
        }

        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }

        /// <summary>
        /// Test the property 'PodIndex'
        /// </summary>
        [Fact]
        public void PodIndexTest()
        {
            // TODO unit test for the property 'PodIndex'
        }

        /// <summary>
        /// Test the property 'Reason'
        /// </summary>
        [Fact]
        public void ReasonTest()
        {
            // TODO unit test for the property 'Reason'
        }

        /// <summary>
        /// Test the property 'ReplicaStatus'
        /// </summary>
        [Fact]
        public void ReplicaStatusTest()
        {
            // TODO unit test for the property 'ReplicaStatus'
        }

        /// <summary>
        /// Test the property 'RestartCount'
        /// </summary>
        [Fact]
        public void RestartCountTest()
        {
            // TODO unit test for the property 'RestartCount'
        }

        /// <summary>
        /// Test the property 'StartTime'
        /// </summary>
        [Fact]
        public void StartTimeTest()
        {
            // TODO unit test for the property 'StartTime'
        }

        /// <summary>
        /// Test the property 'StatusMessage'
        /// </summary>
        [Fact]
        public void StatusMessageTest()
        {
            // TODO unit test for the property 'StatusMessage'
        }
    }
}
