/*
 * Radix job scheduler server.
 *
 * This is the API Server for the Radix job scheduler server.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using RadixJobClient.Api;
using RadixJobClient.Model;
using RadixJobClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace RadixJobClient.Test.Model
{
    /// <summary>
    ///  Class for testing RadixBatch
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class RadixBatchTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for RadixBatch
        //private RadixBatch instance;

        public RadixBatchTests()
        {
            // TODO uncomment below to create an instance of RadixBatch
            //instance = new RadixBatch();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of RadixBatch
        /// </summary>
        [Fact]
        public void RadixBatchInstanceTest()
        {
            // TODO uncomment below to test "IsType" RadixBatch
            //Assert.IsType<RadixBatch>(instance);
        }


        /// <summary>
        /// Test the property 'BatchType'
        /// </summary>
        [Fact]
        public void BatchTypeTest()
        {
            // TODO unit test for the property 'BatchType'
        }
        /// <summary>
        /// Test the property 'CreationTime'
        /// </summary>
        [Fact]
        public void CreationTimeTest()
        {
            // TODO unit test for the property 'CreationTime'
        }
        /// <summary>
        /// Test the property 'Ended'
        /// </summary>
        [Fact]
        public void EndedTest()
        {
            // TODO unit test for the property 'Ended'
        }
        /// <summary>
        /// Test the property 'JobStatuses'
        /// </summary>
        [Fact]
        public void JobStatusesTest()
        {
            // TODO unit test for the property 'JobStatuses'
        }
        /// <summary>
        /// Test the property 'Message'
        /// </summary>
        [Fact]
        public void MessageTest()
        {
            // TODO unit test for the property 'Message'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'Started'
        /// </summary>
        [Fact]
        public void StartedTest()
        {
            // TODO unit test for the property 'Started'
        }
        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Fact]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }

    }

}
