/*
 * Radix job scheduler server.
 *
 * This is the API Server for the Radix job scheduler server.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using RadixJobClient.Model;
using RadixJobClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace RadixJobClient.Test.Model
{
    /// <summary>
    ///  Class for testing ReplicaStatus
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ReplicaStatusTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ReplicaStatus
        //private ReplicaStatus instance;

        public ReplicaStatusTests()
        {
            // TODO uncomment below to create an instance of ReplicaStatus
            //instance = new ReplicaStatus();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ReplicaStatus
        /// </summary>
        [Fact]
        public void ReplicaStatusInstanceTest()
        {
            // TODO uncomment below to test "IsType" ReplicaStatus
            //Assert.IsType<ReplicaStatus>(instance);
        }

        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Fact]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }
    }
}
