/*
 * Radix job scheduler server.
 *
 * This is the API Server for the Radix job scheduler server.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using RadixJobClient.Model;
using RadixJobClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace RadixJobClient.Test.Model
{
    /// <summary>
    ///  Class for testing Resources
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ResourcesTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for Resources
        //private Resources instance;

        public ResourcesTests()
        {
            // TODO uncomment below to create an instance of Resources
            //instance = new Resources();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of Resources
        /// </summary>
        [Fact]
        public void ResourcesInstanceTest()
        {
            // TODO uncomment below to test "IsType" Resources
            //Assert.IsType<Resources>(instance);
        }

        /// <summary>
        /// Test the property 'Limits'
        /// </summary>
        [Fact]
        public void LimitsTest()
        {
            // TODO unit test for the property 'Limits'
        }

        /// <summary>
        /// Test the property 'Requests'
        /// </summary>
        [Fact]
        public void RequestsTest()
        {
            // TODO unit test for the property 'Requests'
        }
    }
}
