/*
 * classification Radix API.
 *
 * This is the API Server for the Radix job scheduler.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using RadixJobClient.Api;
using RadixJobClient.Model;
using RadixJobClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace RadixJobClient.Test.Model
{
    /// <summary>
    ///  Class for testing ResourceRequirements
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ResourceRequirementsTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ResourceRequirements
        //private ResourceRequirements instance;

        public ResourceRequirementsTests()
        {
            // TODO uncomment below to create an instance of ResourceRequirements
            //instance = new ResourceRequirements();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ResourceRequirements
        /// </summary>
        [Fact]
        public void ResourceRequirementsInstanceTest()
        {
            // TODO uncomment below to test "IsType" ResourceRequirements
            //Assert.IsType<ResourceRequirements>(instance);
        }


        /// <summary>
        /// Test the property 'Limits'
        /// </summary>
        [Fact]
        public void LimitsTest()
        {
            // TODO unit test for the property 'Limits'
        }
        /// <summary>
        /// Test the property 'Requests'
        /// </summary>
        [Fact]
        public void RequestsTest()
        {
            // TODO unit test for the property 'Requests'
        }

    }

}
