name: Docker Image CI

on:
  push:
    branches: [ main ]
permissions:
      id-token: write
      contents: read

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Generate build ID
      id: prep
      run: |
        branch=${GITHUB_REF##*/}
        sha=${GITHUB_SHA::8}
        ts=$(date +%s)
        echo "::set-output name=BUILD_ID::${branch}-${sha}-${ts}"
    - name: 'Az CLI login'
      uses: azure/login@v1
      with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  
    - name: 'Run Azure CLI commands'
      run: |
          az account show
    - name: 'Build the Docker image'
      run: docker build . --file Dockerfile.frontend --tag radixdev.azurecr.io/radix-job-demo-fed-test:${{ steps.prep.outputs.BUILD_ID }}
    - name: 'Push the docker image'
      run: docker push radixdev.azurecr.io/radix-job-demo-fed-test:${{ steps.prep.outputs.BUILD_ID }}
