name: Docker Image CI

on:
  push:
    branches: [ "main" ]

permissions:
  id-token: write
  contents: read

jobs:
  list-radix-apps:
    runs-on: ubuntu-latest
    # environment: prod
    steps:
      - name: 'Az CLI login'
        uses: azure/login@v1
        with:
          client-id: b96d264b-7053-4465-a4a7-32be5b0fec49 #5e48ca1f-a2bf-4dec-b96d-bbf8ce69f9f6
          tenant-id: 3aa4a235-b6e2-48d5-9195-7fcf05b459b0
          allow-no-subscriptions: true
      - name: 'Get token for Radix'
        run: |
          token=$(az account get-access-token --resource 6dae42f8-4368-4678-94ff-3960e28e3630 --query=accessToken -otsv)
          echo "::add-mask::$token"
          echo "APP_SERVICE_ACCOUNT_TOKEN=$token" >> $GITHUB_ENV
      - name: List apps in Radix dev cluster
        uses: equinor/radix-github-actions@master
        env:
          APP_SERVICE_ACCOUNT_TOKEN: ${{ env.APP_SERVICE_ACCOUNT_TOKEN }}
        with:
          args: >
            get application
            --context development

      
      

